"""users and games

Revision ID: 351bedbd7c7f
Revises:
Create Date: 2026-10-01 17:07:07.866029

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "351bedbd7c7f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("reputation", sa.Integer(), server_default="50", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=50), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spots", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=6, scale=2), server_default="0", nullable=False),
        sa.Column("min_reputation", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "full",
                "cancelled",
                "played",
                name="gamestatus",
                native_enum=False,
                length=20,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cost >= 0", name="ck_games_cost_not_negative"),
        sa.CheckConstraint(
            "min_reputation BETWEEN 0 AND 100", name="ck_games_min_reputation_range"
        ),
        sa.CheckConstraint("spots BETWEEN 2 AND 30", name="ck_games_spots_range"),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_host_id"), "games", ["host_id"], unique=False)
    op.create_index(op.f("ix_games_sport"), "games", ["sport"], unique=False)
    op.create_index(op.f("ix_games_starts_at"), "games", ["starts_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_starts_at"), table_name="games")
    op.drop_index(op.f("ix_games_sport"), table_name="games")
    op.drop_index(op.f("ix_games_host_id"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
