"""signups and attendance

Revision ID: b8547a9d4de2
Revises: 351bedbd7c7f
Create Date: 2026-10-08 18:39:54.425726

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8547a9d4de2"
down_revision: str | Sequence[str] | None = "351bedbd7c7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("showed_up", sa.Boolean(), nullable=False),
        sa.Column("marked_by", sa.Integer(), nullable=False),
        sa.Column(
            "marked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["marked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "user_id", name="uq_attendance_game_user"),
    )
    op.create_index(op.f("ix_attendance_game_id"), "attendance", ["game_id"], unique=False)
    op.create_index(op.f("ix_attendance_user_id"), "attendance", ["user_id"], unique=False)
    op.create_table(
        "signups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "joined", "waitlist", "removed", name="signupstatus", native_enum=False, length=20
            ),
            server_default="joined",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "user_id", name="uq_signups_game_user"),
    )
    op.create_index(op.f("ix_signups_game_id"), "signups", ["game_id"], unique=False)
    op.create_index(op.f("ix_signups_user_id"), "signups", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signups_user_id"), table_name="signups")
    op.drop_index(op.f("ix_signups_game_id"), table_name="signups")
    op.drop_table("signups")
    op.drop_index(op.f("ix_attendance_user_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_game_id"), table_name="attendance")
    op.drop_table("attendance")
    # ### end Alembic commands ###
